#!/bin/sh /etc/rc.common 
 
 START = 99 
 STOP = 10 
 
 USE_PROCD = 1 
 PROG = /root/mesh-node-daemon.sh 
 
 start_service ( ) { 
    procd_open_instance 
    procd_set_param  command $PROG 
    procd_set_param respawn  3600 5 0 # Respawn if killed 
    procd_set_param stdout  1 
    procd_set_param stderr  1 
    procd_close_instance 
 echo "Mesh node daemon started" 
 } 
 
 stop_service ( ) { 
 killall  mesh-node-daemon.sh 
 echo "Mesh node daemon stopped" 
 }
